### ISSUE TITLE
Crash (bis): IllegalArgumentException on onRestoreInstanceState

### ISSUE THREAD

**Issue by soncaokim** [vinyl2-team/vinyl2#22]
App version: 1.4.0-cont-integ_96947b33_230120-2019 CI
App version code: 178
Android build version: 6b3ba99e23
Android release version: 13
Android SDK version: 33
Android build ID: lineage_cheeseburger-userdebug 13 TQ1A.230105.001.A2 6b3ba99e23
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus5
Device model: ONEPLUS A5000
Device product name: OnePlus5
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sat Jan 21 00:17:35 GMT+01:00 2023

Stack:
```
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class androidx.appcompat.widget.Toolbar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/cab_stub_playlist. Make sure other views do not use the same id.
	at android.view.View.onRestoreInstanceState(View.java:21594)
	at android.view.View.dispatchRestoreInstanceState(View.java:21566)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4007)
	at android.view.View.restoreHierarchyState(View.java:21544)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2216)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1768)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1721)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1464)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3686)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by soncaokim** [comment]
This replaces #18
