### ISSUE TITLE
Crash, Android 12/13: java.lang.IllegalStateException: Animator has already started, cannot change it now!

### ISSUE THREAD

**Issue by soncaokim** [vinyl2-team/vinyl2#5]
Crash collected on : Mon Jan 02 21:52:45 GMT+01:00 2023

Informations :
```
Locale: en_US
Version: 1.3.0-cont-integ_94ec3cf5_220806-1540 CI
Package: [com.poupa.vinylmusicplayer.ci](http://com.poupa.vinylmusicplayer.ci/)
Phone Model: ONEPLUS A6003
Android Version: 13
Board: sdm845
Brand: OnePlus
Device: OnePlus6
Host: 813445d10b11
ID: TQ1A.221205.011
Model: ONEPLUS A6003
Product: OnePlus6
Type: userdebug
Total Internal memory: 113872437248
Available Internal memory: 30010892288
```

Stack:
```
java.lang.IllegalStateException: Animator has already started, cannot change it now!
at android.graphics.animation.RenderNodeAnimator.checkMutable(RenderNodeAnimator.java:138)
at android.graphics.animation.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:314)
at android.graphics.animation.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:37)
at android.animation.AnimatorSet.updateAnimatorsDuration(AnimatorSet.java:774)
at android.animation.AnimatorSet.getTotalDuration(AnimatorSet.java:1744)
at android.animation.AnimationHandler.lambda$new$0$android-animation-AnimationHandler(AnimationHandler.java:224)
at android.animation.AnimationHandler$$ExternalSyntheticLambda0.doFrame(Unknown Source:2)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:827)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by soncaokim** [comment]
Possibly related to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/620 and https://github.com/AdrienPoupa/VinylMusicPlayer/pull/639

**Comment by soncaokim** [comment]
Fixed by https://github.com/AdrienPoupa/VinylMusicPlayer/pull/639
